-- MySQL Script generated by MySQL Workbench
-- 09/14/16 19:03:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sge` DEFAULT CHARACTER SET utf8 ;
USE `sge` ;

-- -----------------------------------------------------
-- Table `sge`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`evento` (
  `idevento` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` CHAR(30) NOT NULL,
  `nome` CHAR(30) NOT NULL,
  `descricao` CHAR(30) NOT NULL,
  `dtinicio` CHAR(30) NOT NULL,
  `dttermino` CHAR(50) NOT NULL,
  `qtdevagas` CHAR(50) NOT NULL,
  `horario` CHAR(50) NOT NULL,
  `url` VARCHAR(50) NULL DEFAULT NULL,
  `status` CHAR(50) NOT NULL,
  PRIMARY KEY (`idevento`))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sge`.`conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`conteudo` (
  `idconteudo` INT(11) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `conteudo` VARCHAR(45) NULL DEFAULT NULL,
  `idevento` INT(11) NOT NULL,
  PRIMARY KEY (`idevento`),
  CONSTRAINT `fk_conteudo_evento1`
    FOREIGN KEY (`idevento`)
    REFERENCES `sge`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sge`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` CHAR(30) NOT NULL,
  `cpf` CHAR(50) NOT NULL,
  `endereco` CHAR(50) NOT NULL,
  `email` CHAR(50) NOT NULL,
  `senha` CHAR(50) NOT NULL,
  `tipo` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sge`.`usuarioevento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`usuarioevento` (
  `idusuario` INT(10) NOT NULL,
  `idevento` INT(10) NOT NULL,
  `idusuarioevento` INT(10) NOT NULL,
  PRIMARY KEY (`idusuario`, `idevento`, `idusuarioevento`),
  INDEX `fk_usuario_has_evento_evento1_idx` (`idevento` ASC),
  INDEX `fk_usuario_has_evento_usuario1_idx` (`idusuario` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
